import { Button, Input } from "antd";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Contact Form</h1>
        <form
          name="contact"
          method="POST"
          data-netlify="true"
          data-netlify-honeypot="bot-field">
          <Input type="hidden" name="form-name" value="contact" />
          <div hidden>
            <Input name="bot-field" />
          </div>
          <p>
            <label>
              Your Name: <Input type="text" name="name" />
            </label>
          </p>
          <p>
            <label>
              Your Email: <Input type="email" name="email" />
            </label>
          </p>

          <p>
            <label>
              Message: <Input.TextArea name="message"></Input.TextArea>
            </label>
          </p>
          <p>
            <Button type="primary" htmlType="submit">CONFIRM</Button>
          </p>
        </form>
      </main>
    </div>
  );
}
